import fs from 'node:fs';
const root=new URL('./src/',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const engine=read('battle/engine.js'),heroes=read('data/heroes.js'),custom=read('data/customHeroes.js'),skills=read('utils/skills.js'),battle=read('pages/BattlePage.jsx'),context=read('store/GameContext.jsx'),elements=read('utils/elements.js');
const checks=[];const check=(name,ok)=>{checks.push({name,ok});if(!ok)throw new Error(name)};
check('26 champions et 78 compétences',([...heroes.matchAll(/\{id:\d+/g),...custom.matchAll(/\{id:\d+/g)].length===26)&&([...heroes.matchAll(/S\('/g)].length+([...custom.matchAll(/\[\'/g)].length/1)>=78));
for(const key of ['poison','burn','bleed','agony','corruption'])check(`DOT ${key}`,engine.includes(`debuffs.${key}`));
for(const key of ['healingSeed','healingTotem','livingGarden','regen'])check(`persistant ${key}`,engine.includes(key));
for(const key of ['guardianLink','provoke','shield','rescue'])check(`protection ${key}`,engine.toLowerCase().includes(key.toLowerCase()));
for(const key of ['holyPower','feral','rogue','arcane','festering','soul'])check(`ressource ${key}`,engine.includes(key));
check('critique garanti Visée',engine.includes('forceCrit=m.active'));
check('critique garanti Disparition',engine.includes("e==='rogueFinish'){bonus"));
check('pénétration',engine.includes('pierce=true'));
check('affinité sur effets',engine.includes('chance+relation.effect'));
check('Précision/Résistance',engine.includes('debuffChance'));
check('maîtrises utilisées',engine.includes('mastery.duration')&&engine.includes('mastery.effectRate')&&engine.includes('mastery.power')&&engine.includes('mastery.cooldown'));
check('événements structurés',engine.includes("type:'damage'")&&engine.includes("type:'shield'")&&battle.includes("event.type==='dot'"));
check('effets uniques visibles',battle.includes('atonement')&&battle.includes('healingTotem')&&battle.includes('festering'));
check('persistance battle complet',context.includes('battleSession')&&context.includes('updateBattleSession')&&battle.includes('updateBattleSession({battle:next})'));
check('cycles élémentaires',elements.includes("Feu:'Nature'")&&elements.includes("Arcane:'Ombre'"));
console.log(JSON.stringify({passed:checks.length,total:checks.length,checks},null,2));
