import React,{useMemo,useState}from'react';
import{useGame}from'../store/GameContext';
import{ACHIEVEMENTS,ACHIEVEMENT_CATEGORIES,achievementProgress,achievementReady,achievementScore}from'../data/achievements';
const rewardParts=reward=>[reward.gold&&`🪙 ${reward.gold.toLocaleString('fr-FR')}`,reward.gems&&`💎 ${reward.gems.toLocaleString('fr-FR')}`,reward.essence&&`🔹 ${reward.essence.toLocaleString('fr-FR')}`,reward.stones&&`🔥 ${reward.stones.toLocaleString('fr-FR')}`,reward.masteryTomes&&`📘 ${reward.masteryTomes.toLocaleString('fr-FR')}`,reward.universalSoul5&&`🧩 ${reward.universalSoul5.toLocaleString('fr-FR')}`,reward.gear&&`🎁 ${reward.gear.slot} · ${reward.gear.setId} · 1★`,reward.gearPack&&`🎁 ${reward.gearPack.length} pièces d’équipement 1★`].filter(Boolean);
const fmt=value=>Math.max(0,Number(value)||0).toLocaleString('fr-FR');
export default function AchievementsPage(){
 const game=useGame();
 const[message,setMessage]=useState(null),[pending,setPending]=useState(null),[category,setCategory]=useState('Tous'),[status,setStatus]=useState('all'),[query,setQuery]=useState('');
 const state={campaign:game.campaign,expeditionProgress:game.expeditionProgress,raidProgress:game.raidProgress,mythicProgress:game.mythicProgress,owned:game.owned,championProgress:game.championProgress,forgeHistory:game.forgeHistory,inventory:game.inventory,history:game.history,legendaryChronicles:game.legendaryChronicles,progressionStats:game.progressionStats};
 const claimed=Object.keys(game.achievementClaims||{}).length,completed=ACHIEVEMENTS.filter(item=>achievementReady(item,state)).length,readyCount=ACHIEVEMENTS.filter(item=>achievementReady(item,state)&&!game.achievementClaims?.[item.id]).length,score=achievementScore(state,game.achievementClaims),completion=Math.round(completed/Math.max(1,ACHIEVEMENTS.length)*100);
 const categoryReady=useMemo(()=>Object.fromEntries(ACHIEVEMENT_CATEGORIES.map(name=>[name,ACHIEVEMENTS.filter(item=>(name==='Tous'||item.category===name)&&achievementReady(item,state)&&!game.achievementClaims?.[item.id]).length])),[game.achievementClaims,game.progressionStats,game.campaign,game.championProgress,game.inventory,game.legendaryChronicles]);
 const filtered=useMemo(()=>ACHIEVEMENTS.filter(item=>{const ready=achievementReady(item,state),done=Boolean(game.achievementClaims?.[item.id]),categoryMatch=category==='Tous'||item.category===category,statusMatch=status==='all'||(status==='ready'&&ready&&!done)||(status==='claimed'&&done)||(status==='locked'&&!ready),text=`${item.name} ${item.description} ${item.category} ${item.group||''}`.toLowerCase();return categoryMatch&&statusMatch&&(!query||text.includes(query.toLowerCase()))}),[category,status,query,game.achievementClaims,game.progressionStats,game.campaign,game.championProgress,game.inventory,game.legendaryChronicles]);
 return <section className="achievements-page achievements-v3">
  <header className="achievement-heading-v3"><div><small>PROGRESSION PERMANENTE · DÉBUT AU LATE GAME</small><h2>🏆 Hauts faits</h2><p>Chaque activité, style de combat et étape majeure contribue à la progression globale.</p></div><div className="achievement-score-orb"><small>SCORE</small><b>{fmt(score)}</b></div></header>
  <div className="achievement-overview-v3"><article><small>Complétion</small><b>{completion} %</b><div className="achievement-global-track"><i style={{width:`${completion}%`}}/></div></article><article><small>Terminés</small><b>{completed}/{ACHIEVEMENTS.length}</b></article><article><small>Réclamés</small><b>{claimed}</b></article><article className={readyCount?'ready-summary':''}><small>À réclamer</small><b>{readyCount}</b></article></div>
  {message&&<p className={message.ok?'achievement-message success':'achievement-message error'}>{message.message}</p>}
  <div className="achievement-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher un haut fait, un champion ou une activité..."/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Tous les états</option><option value="ready">À réclamer</option><option value="locked">En progression</option><option value="claimed">Réclamés</option></select><span>{filtered.length} résultat{filtered.length>1?'s':''}</span></div>
  <div className="achievement-category-tabs">{ACHIEVEMENT_CATEGORIES.map(item=><button key={item} className={category===item?'selected':''} onClick={()=>setCategory(item)}>{item}{categoryReady[item]>0&&<em>{categoryReady[item]}</em>}</button>)}</div>
  <div className="achievement-grid">{filtered.map(item=>{const progress=achievementProgress(item,state),ready=achievementReady(item,state),done=Boolean(game.achievementClaims?.[item.id]),percent=Math.min(100,Math.round(progress.current/progress.goal*100));return <article key={item.id} className={`achievement-card ${done?'claimed':ready?'ready':'locked'}`}><div className="achievement-card-top"><span>{item.icon}</span><div><small>{item.category}{item.group?` · ${item.group}`:''}</small><h3>{item.name}</h3></div><b>{done?'✓ Réclamé':ready?'✦ Terminé':`${percent} %`}</b></div><p>{item.description}</p>{item.detail&&<small className="achievement-detail">{item.detail}</small>}<div className="achievement-progress"><div><span>Progression</span><b>{fmt(progress.current)}/{fmt(progress.goal)}</b></div><div><i style={{width:`${percent}%`}}/></div></div><div className="achievement-card-footer"><div className="achievement-reward"><small>RÉCOMPENSE</small>{rewardParts(item.reward).map(part=><b key={part}>{part}</b>)}<em>+{item.score||0} score</em></div><button disabled={!ready||done} onClick={()=>{if(pending)return;setPending(item.id);setMessage(game.claimAchievement(item.id));setTimeout(()=>setPending(null),250)}}>{done?'Récompense réclamée':ready?'Réclamer':'Objectif en cours'}</button></div></article>})}</div>
  {!filtered.length&&<p className="achievement-empty">Aucun haut fait ne correspond aux filtres.</p>}
 </section>
}
