import React,{useMemo,useState}from'react';
import{useGame}from'../store/GameContext';
import{Stats}from'../components/Cards';
import{SLOTS,QUALITIES,SETS,STAT_LABELS,effectiveMainValue,formatItemValue,effectiveSubstats,activeSets,nextMilestone,ITEM_MAX_UPGRADE}from'../data/items';

const StatLine=({item})=>{const main=effectiveMainValue(item),substats=effectiveSubstats(item);return <div className="gear-stats"><b>{STAT_LABELS[item.mainStat]} +{formatItemValue(main)}{main>item.mainValue&&<em> (+{formatItemValue(main-item.mainValue)})</em>}</b>{Object.entries(substats).map(([key,value])=><small key={key}>{STAT_LABELS[key]} +{value}</small>)}</div>};
export default function EquipmentPage(){
  const{HEROES,owned,equipment,inventory,equipItem,itemOwner,unequipSlot,sellItem,itemSellValue,toggleItemLock,stats,naturalStats,gold,forgeEssence,upgradeItem,getItemUpgradeCost,recycleItem,itemRecycleValue}=useGame();
  const[selected,setSelected]=useState(owned[0]),[slot,setSlot]=useState('Tous'),[quality,setQuality]=useState('Toutes'),[setId,setSetId]=useState('Tous'),[mainStat,setMainStat]=useState('Toutes'),[subStat,setSubStat]=useState('Toutes'),[availability,setAvailability]=useState('free'),[saleItem,setSaleItem]=useState(null),[upgradeItemModal,setUpgradeItemModal]=useState(null),[recycleItemModal,setRecycleItemModal]=useState(null),[transferItem,setTransferItem]=useState(null),[message,setMessage]=useState(null),[pending,setPending]=useState(null);
  const hero=HEROES.find(entry=>entry.id===selected)||HEROES.find(entry=>owned.includes(entry.id))||HEROES[0],gear=equipment[hero.id]||{};
  const handleEquip=item=>{const owner=itemOwner(item.id),replacedId=gear[item.slot],replaced=inventory.find(entry=>entry.id===replacedId);if((owner&&owner.heroId!==hero.id)||(replaced&&replaced.id!==item.id))return setTransferItem({item,owner,replaced});setMessage(equipItem(hero.id,item.id));};
  const confirmTransfer=()=>{if(!transferItem)return;setMessage(equipItem(hero.id,transferItem.item.id));setTransferItem(null);};
  const refreshModalItem=(setter,id)=>setter(inventory.find(entry=>entry.id===id)||null);
  const confirmUpgrade=()=>{if(!upgradeItemModal||pending)return;setPending(`upgrade:${upgradeItemModal.id}`);const result=upgradeItem(upgradeItemModal.id);setMessage(result);if(result.ok)refreshModalItem(setUpgradeItemModal,upgradeItemModal.id);setTimeout(()=>setPending(null),250)};
  const confirmRecycle=()=>{if(!recycleItemModal||pending)return;setPending(`recycle:${recycleItemModal.id}`);const result=recycleItem(recycleItemModal.id);setMessage(result);setRecycleItemModal(null);setTimeout(()=>setPending(null),250)};
  const confirmSale=()=>{if(!saleItem||pending)return;setPending(`sale:${saleItem.id}`);setMessage(sellItem(saleItem.id));setSaleItem(null);setTimeout(()=>setPending(null),250)};
  const equippedItems=Object.values(gear).map(id=>inventory.find(item=>item.id===id)).filter(Boolean),sets=activeSets(equippedItems);
  const statOptions=useMemo(()=>Object.keys(STAT_LABELS).filter(key=>key!=='spdPct'),[]);
  const filtered=useMemo(()=>inventory.filter(item=>{const owner=itemOwner(item.id),matchesAvailability=availability==='all'||(availability==='free'&&!owner)||(availability==='equipped'&&Boolean(owner))||(availability==='locked'&&item.locked);return(slot==='Tous'||item.slot===slot)&&(quality==='Toutes'||item.quality===quality)&&(setId==='Tous'||item.setId===setId)&&(mainStat==='Toutes'||item.mainStat===mainStat)&&(subStat==='Toutes'||Object.prototype.hasOwnProperty.call(effectiveSubstats(item),subStat))&&matchesAvailability}).sort((a,b)=>{const ownerA=itemOwner(a.id),ownerB=itemOwner(b.id),rank=owner=>!owner?0:owner.heroId===hero.id?1:2;return rank(ownerA)-rank(ownerB)}),[inventory,slot,quality,setId,mainStat,subStat,availability,hero.id,equipment]);
  const resetFilters=()=>{setSlot('Tous');setQuality('Toutes');setSetId('Tous');setMainStat('Toutes');setSubStat('Toutes');setAvailability('free');};
  const filtersActive=[slot!=='Tous',quality!=='Toutes',setId!=='Tous',mainStat!=='Toutes',subStat!=='Toutes',availability!=='free'].some(Boolean);
  return <section className="stuff-page"><div className="equipment-heading"><div><h2>🎒 Arsenal et Forge</h2><p>{inventory.length} objets · amélioration garantie jusqu’à +15</p></div><div className="forge-heading-wallet"><span>🪙 {gold.toLocaleString('fr-FR')}</span><span>🔹 {forgeEssence.toLocaleString('fr-FR')}</span><b>{inventory.length}/300</b></div></div>
    <div className="tabs">{HEROES.filter(entry=>owned.includes(entry.id)).map(entry=><button key={entry.id} className={selected===entry.id?'active':''} onClick={()=>setSelected(entry.id)}>{entry.icon} {entry.name}</button>)}</div>
    <div className="stuff-workspace"><aside className="equipped-pane"><div className="equipped-grid">{SLOTS.map(name=>{const item=inventory.find(value=>value.id===gear[name]);return <article key={name} className={`equipped-slot ${item?'filled':''}`}><strong>{name}</strong>{item?<><b style={{color:QUALITIES[item.quality].color}}>{item.icon} {item.name} <i>+{item.level||0}</i></b><span>{'★'.repeat(item.stars)} · niv. objet {item.itemLevel}</span><small className="equipped-set-line">{SETS[item.setId].icon} Set {SETS[item.setId].name} · {QUALITIES[item.quality].name}</small><StatLine item={item}/>{(()=>{const cost=getItemUpgradeCost(item.id);return <div className="equipped-upgrade-preview">{cost?<><small>Prochaine amélioration +{cost.target}</small><b>🪙 {cost.gold.toLocaleString('fr-FR')} · 🔹 {cost.essence}</b></>:<b>Amélioration maximale</b>}</div>})()}<div className="equipped-slot-actions"><button className="upgrade-action" disabled={!getItemUpgradeCost(item.id)} onClick={()=>setUpgradeItemModal(item)}>🔨 Améliorer</button><button onClick={()=>unequipSlot(hero.id,name)}>Retirer</button></div></>:<small>Emplacement vide</small>}</article>})}</div>
    <div className="active-sets"><h3>Bonus de sets</h3>{sets.length?sets.map((id,index)=><span key={`${id}-${index}`}>{SETS[id].icon} {SETS[id].name} : {SETS[id].bonus}</span>):<small>Aucun bonus actif</small>}</div>
    <Stats s={stats(hero)} base={{hp:hero.hp,atk:hero.atk,def:hero.def,spd:hero.spd,crit:5,accuracy:hero.accuracy||0,resistance:hero.resistance||15}} progressed={naturalStats(hero)}/>
    {message&&<p className={message.ok?'equipment-message success':'equipment-message error'}>{message.message}</p>}
    </aside><section className="inventory-pane"><div className="gear-filters equipment-stat-filters"><select aria-label="Filtrer par disponibilité" value={availability} onChange={event=>setAvailability(event.target.value)}><option value="all">Tous</option><option value="free">Non équipés</option><option value="equipped">Équipés</option><option value="locked">Verrouillés</option></select><select aria-label="Filtrer par emplacement" value={slot} onChange={event=>setSlot(event.target.value)}><option>Tous</option>{SLOTS.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filtrer par qualité" value={quality} onChange={event=>setQuality(event.target.value)}><option>Toutes</option>{Object.entries(QUALITIES).map(([id,value])=><option key={id} value={id}>{value.name}</option>)}</select><select aria-label="Filtrer par set" value={setId} onChange={event=>setSetId(event.target.value)}><option value="Tous">Tous les sets</option>{Object.entries(SETS).map(([id,value])=><option key={id} value={id}>{value.name}</option>)}</select><select aria-label="Filtrer par statistique principale" value={mainStat} onChange={event=>setMainStat(event.target.value)}><option value="Toutes">Toutes stats principales</option>{statOptions.map(key=><option key={key} value={key}>{STAT_LABELS[key]}</option>)}</select><select aria-label="Filtrer par statistique secondaire" value={subStat} onChange={event=>setSubStat(event.target.value)}><option value="Toutes">Toutes stats secondaires</option>{statOptions.map(key=><option key={key} value={key}>{STAT_LABELS[key]}</option>)}</select><button type="button" className="filter-reset" disabled={!filtersActive} onClick={resetFilters}>Réinitialiser</button><b>{filtered.length} objet(s)</b></div>
    <div className="gear-inventory">{filtered.map(item=>{const owner=itemOwner(item.id),equipped=Boolean(owner),equippedHere=owner?.heroId===hero.id,cost=getItemUpgradeCost(item.id),milestone=nextMilestone(item.level);return <article key={item.id} className="generated-item forge-item" style={{'--quality':QUALITIES[item.quality].color}}><div className="item-title"><b>{item.icon} {item.name}</b><span>{QUALITIES[item.quality].name}</span></div><div className="item-rank-line"><span className="item-stars">{'★'.repeat(item.stars)}{'☆'.repeat(5-item.stars)}</span><b className="upgrade-level">+{item.level||0}</b></div><small>Niveau d’objet {item.itemLevel} · Set {SETS[item.setId].name}</small><StatLine item={item}/>{owner&&<div className={`item-owner-badge ${equippedHere?'current-owner':'other-owner'}`}>👤 Équipé par <b>{owner.hero.icon} {owner.hero.name}</b></div>}{item.upgradeRolls?.length>0&&<div className="upgrade-roll-summary">{item.upgradeRolls.slice(-2).map((roll,index)=><small key={`${roll.level}-${index}`}>+{roll.level} · {roll.type==='add'?'Nouvelle':'Améliorée'} : {STAT_LABELS[roll.stat]} +{roll.value}</small>)}</div>}<small className="item-source">{item.source}</small><div className="forge-next">{item.level>=ITEM_MAX_UPGRADE?<b>AMÉLIORATION MAXIMALE</b>:<><span>Prochain niveau : +{item.level+1}</span><small>{milestone?`Prochain palier secondaire : +${milestone}`:'Tous les paliers obtenus'}</small></>}</div><div className="item-actions forge-actions"><button className="equip-action" disabled={equippedHere} onClick={()=>handleEquip(item)}>{equippedHere?`✓ Équipé par ${hero.name}`:owner?`Transférer à ${hero.name}`:'Équiper'}</button><button className="upgrade-action" disabled={!cost} onClick={()=>setUpgradeItemModal(item)}>🔨 Améliorer</button><button onClick={()=>toggleItemLock(item.id)}>{item.locked?'🔒':'🔓'}</button><button className="danger" disabled={item.locked||equipped} onClick={()=>setSaleItem(item)}>Vendre</button><button className="recycle-action" disabled={item.locked||equipped} onClick={()=>setRecycleItemModal(item)}>🔹 Recycler</button></div></article>})}</div></section></div>
    {saleItem&&<div className="sale-modal-backdrop" onClick={()=>setSaleItem(null)}><div className="sale-modal" onClick={event=>event.stopPropagation()}><div className="sale-modal-icon">🪙</div><h3>Vendre cet équipement ?</h3><b style={{color:QUALITIES[saleItem.quality].color}}>{saleItem.icon} {saleItem.name} +{saleItem.level||0}</b><div className="sale-gold-value"><small>Or récupéré</small><strong>🪙 {itemSellValue(saleItem).toLocaleString('fr-FR')}</strong></div><p>Cette action est définitive.</p><div className="sale-modal-actions"><button className="secondary" onClick={()=>setSaleItem(null)}>Annuler</button><button className="danger" onClick={confirmSale}>Vendre</button></div></div></div>}
    {upgradeItemModal&&(()=>{const current=inventory.find(entry=>entry.id===upgradeItemModal.id)||upgradeItemModal,cost=getItemUpgradeCost(current.id),before=effectiveMainValue(current),after=cost?Math.round(current.mainValue*(1+cost.target*.04)*10)/10:before;return <div className="forge-modal-backdrop" onClick={()=>setUpgradeItemModal(null)}><div className="forge-modal" onClick={event=>event.stopPropagation()}><div className="forge-modal-icon">🔨</div><h3>{cost?`Amélioration +${current.level||0} → +${cost.target}`:'Amélioration maximale'}</h3><b style={{color:QUALITIES[current.quality].color}}>{current.icon} {current.name}</b><div className="forge-stat-preview"><small>{STAT_LABELS[current.mainStat]}</small><strong>{formatItemValue(before)} → {formatItemValue(after)}</strong></div>{cost&&<><div className="forge-cost"><span>🪙 {cost.gold.toLocaleString('fr-FR')}</span><span>🔹 {cost.essence}</span></div><p>{cost.milestone?Object.keys(effectiveSubstats(current)).length<4?'Ce palier ajoutera une nouvelle statistique secondaire.':'Ce palier améliorera une statistique secondaire aléatoire.':`Prochain palier secondaire : +${nextMilestone(current.level)}`}</p></>}<div className="forge-modal-actions"><button className="secondary" onClick={()=>setUpgradeItemModal(null)}>Fermer</button><button disabled={!cost||gold<cost.gold||forgeEssence<cost.essence} onClick={confirmUpgrade}>{cost?'Améliorer':'Maximum'}</button></div></div></div>})()}
    {transferItem&&<div className="forge-modal-backdrop" onClick={()=>setTransferItem(null)}><div className="forge-modal transfer-modal" onClick={event=>event.stopPropagation()}><div className="forge-modal-icon">🔄</div><h3>{transferItem.owner?'Transférer cet équipement ?':'Remplacer cet équipement ?'}</h3><b style={{color:QUALITIES[transferItem.item.quality].color}}>{transferItem.item.icon} {transferItem.item.name} +{transferItem.item.level||0}</b><div className="transfer-route"><div><small>Actuellement équipé par</small><strong>{transferItem.owner?`${transferItem.owner.hero.icon} ${transferItem.owner.hero.name}`:'Personne'}</strong></div><span>→</span><div><small>Nouvel utilisateur</small><strong>{hero.icon} {hero.name}</strong></div></div>{transferItem.replaced&&transferItem.replaced.id!==transferItem.item.id&&<div className="transfer-replaced"><small>{hero.name} porte déjà :</small><b>{transferItem.replaced.icon} {transferItem.replaced.name} +{transferItem.replaced.level||0}</b><span>Cette pièce sera retirée et restera dans l’inventaire.</span></div>}<p>{transferItem.owner&&transferItem.owner.heroId!==hero.id?`${transferItem.item.name} sera automatiquement retiré de ${transferItem.owner.hero.name}.`:''} Aucun équipement ne sera supprimé.</p><div className="forge-modal-actions"><button className="secondary" onClick={()=>setTransferItem(null)}>Annuler</button><button className="transfer-confirm" onClick={confirmTransfer}>{transferItem.owner?`Transférer à ${hero.name}`:`Équiper sur ${hero.name}`}</button></div></div></div>}
    {recycleItemModal&&<div className="forge-modal-backdrop" onClick={()=>setRecycleItemModal(null)}><div className="forge-modal recycle-modal" onClick={event=>event.stopPropagation()}><div className="forge-modal-icon">♻️</div><h3>Recycler cet équipement ?</h3><b style={{color:QUALITIES[recycleItemModal.quality].color}}>{recycleItemModal.icon} {recycleItemModal.name} +{recycleItemModal.level||0}</b><span>{'★'.repeat(recycleItemModal.stars)} · {QUALITIES[recycleItemModal.quality].name}</span><div className="recycle-value"><small>Essences récupérées</small><strong>🔹 {itemRecycleValue(recycleItemModal)}</strong></div><p>25 % des Essences investies sont récupérées. Les objets de Boutique rendent 50 % de la valeur normale. L’or n’est pas remboursé.</p><div className="forge-modal-actions"><button className="secondary" onClick={()=>setRecycleItemModal(null)}>Annuler</button><button className="recycle-action" onClick={confirmRecycle}>Recycler</button></div></div></div>}
  </section>;
}
