import React,{useEffect,useState}from'react';
import{useGame}from'../store/GameContext';
import{EXPEDITIONS,EXPEDITION_DAILY_SEALS,EXPEDITION_HONOR_WINS,expeditionHonorForDate,expeditionHonorReward,expeditionLevelData,createExpeditionMission}from'../data/expeditions';
import{EXPEDITION_SET_POOLS,SETS}from'../data/items'; import EnemyInfoModal from'../components/EnemyInfoModal';

const Readiness=({assessment})=><section className={`readiness-panel compact-readiness ${assessment.verdict.key}`}><header><div><small>ESTIMATION GLOBALE</small><b>{assessment.verdict.icon} {assessment.verdict.label}</b></div><strong>{assessment.score}/100</strong></header><div className="readiness-bars"><span><small>Dégâts</small><i><b style={{width:`${assessment.checks.damage}%`}}/></i><em>{assessment.checks.damage}%</em></span><span><small>Survie</small><i><b style={{width:`${assessment.checks.survival}%`}}/></i><em>{assessment.checks.survival}%</em></span><span><small>Tempo</small><i><b style={{width:`${assessment.checks.tempo}%`}}/></i><em>{assessment.checks.tempo}%</em></span></div></section>;
export default function ExpeditionsPage({setPage}){
 const{expeditionProgress,forgeEssence,ascensionEssences,teamPower,assessMission,requestMissionStart,chooseSundayExpeditionHonor,claimExpeditionHonor}=useGame();const[selected,setSelected]=useState('treasury'),[level,setLevel]=useState(1),[now,setNow]=useState(Date.now()),[enemyInfo,setEnemyInfo]=useState(null),[honorMessage,setHonorMessage]=useState(''),[launching,setLaunching]=useState(false);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const activity=EXPEDITIONS.find(x=>x.id===selected)||EXPEDITIONS[0],maxUnlocked=Math.min(10,(expeditionProgress.completed?.[selected]||0)+1),data=expeditionLevelData(selected,level),expeditionMission=createExpeditionMission(selected,level),assessment=assessMission(expeditionMission);
 const next=new Date();next.setHours(24,0,0,0);const remaining=Math.max(0,next.getTime()-now),h=Math.floor(remaining/3600000),m=Math.floor(remaining%3600000/60000);
 const honor=expeditionProgress.honor||{},isSunday=new Date(now).getDay()===0,featuredId=expeditionHonorForDate(new Date(now),honor.sundayChoice),featured=EXPEDITIONS.find(entry=>entry.id===featuredId),honorReward=expeditionHonorReward(featuredId),honorWins=Math.min(EXPEDITION_HONOR_WINS,honor.wins||0),honorReady=honorWins>=EXPEDITION_HONOR_WINS&&!honor.claimed;
 const launch=()=>{if(launching||level>maxUnlocked)return;setLaunching(true);const result=requestMissionStart(createExpeditionMission(selected,level));if(result.ok)setPage('battle');else setHonorMessage(result.message||'Impossible de préparer cette Expédition.');setTimeout(()=>setLaunching(false),250)};
 return <section className="expeditions-page"><section className={`expedition-honor ${honorReady?'ready':''} ${honor.claimed?'claimed':''}`}><header><div><small>EXPÉDITION À L’HONNEUR</small><h3>{featured?`${featured.icon} ${featured.name}`:'✨ Choix du dimanche'}</h3><p>{featured?`Remporte ${EXPEDITION_HONOR_WINS} victoires récompensées dans cette Expédition.`:'Choisis l’activité mise à l’honneur pour aujourd’hui.'}</p></div><strong>{honor.claimed?'✓ Coffre récupéré':honorReady?'🎁 Coffre disponible':`${honorWins}/${EXPEDITION_HONOR_WINS}`}</strong></header>{isSunday&&!featured&&<div className="honor-sunday-choice">{EXPEDITIONS.map(item=><button key={item.id} style={{'--expedition-color':item.color}} onClick={()=>{const result=chooseSundayExpeditionHonor(item.id);setHonorMessage(result.message);if(result.ok)setSelected(item.id)}}>{item.icon}<span>{item.rewardName}</span></button>)}</div>}{featured&&<><div className="honor-progress"><i><b style={{width:`${honorWins/EXPEDITION_HONOR_WINS*100}%`}}/></i><span>{honorWins}/{EXPEDITION_HONOR_WINS}</span></div><div className="honor-reward"><small>Récompense fixe</small><b>{honorReward?.label}</b><button disabled={!honorReady} onClick={()=>{const result=claimExpeditionHonor();setHonorMessage(result.message)}}>{honor.claimed?'Coffre récupéré':honorReady?'Réclamer le coffre':'Objectif en cours'}</button></div></>}{honorMessage&&<p className="honor-message">{honorMessage}</p>}</section><div className="expedition-heading"><div><small>ACTIVITÉS QUOTIDIENNES</small><h2>⚔️ Expéditions</h2><p>Choisis où investir tes Sceaux entre or, expérience, Essence de forge et Essences d’Ascension. Un Sceau est consommé uniquement après une victoire récompensée.</p></div><div className="seal-counter"><span>🔑</span><div><small>Sceaux disponibles</small><b>{expeditionProgress.seals}/{EXPEDITION_DAILY_SEALS}</b><em>Reset dans {h} h {m} min</em></div></div></div><p className="seal-rule">🔑 Aucun Sceau n’est consommé en cas de défaite ou d’abandon. Le Sceau est retiré uniquement après une victoire récompensée.</p><div className="forge-wallet">🔹 Essence de forge : <b>{forgeEssence.toLocaleString('fr-FR')}</b><small>Utilisée dans Stuff pour améliorer les équipements jusqu’à +15. Les objets inutiles peuvent aussi être recyclés.</small></div><div className="ascension-wallet"><span>🔹 {ascensionEssences.minor}</span><span>🔷 {ascensionEssences.major}</span><span>💠 {ascensionEssences.mythic}</span><small>Conversion 10 pour 1 disponible dans l’Inventaire.</small></div>
 <div className="expedition-types">{EXPEDITIONS.map(item=><button key={item.id} className={`${selected===item.id?'selected':''} ${featuredId===item.id?'honored':''}`} style={{'--expedition-color':item.color}} onClick={()=>{setSelected(item.id);setLevel(1)}}><span>{item.icon}</span>{featuredId===item.id&&<mark>⭐ À L’HONNEUR</mark>}<strong>{item.name}</strong><small>{item.description}</small><em>{item.rewardIcon} {item.rewardName}</em><b>Progression {expeditionProgress.completed?.[item.id]||0}/10</b></button>)}</div>
 <article className="expedition-detail" style={{'--expedition-color':activity.color}}><div className="expedition-title"><span>{activity.icon}</span><div><h3>{activity.name}</h3><p>{activity.description}</p></div><b>{typeof data.reward==='number'?`${activity.rewardIcon} ${data.reward.toLocaleString('fr-FR')}`:[data.reward.minor&&`🔹 ${data.reward.minor}`,data.reward.major&&`🔷 ${data.reward.major}`,data.reward.mythic&&`💠 ${data.reward.mythic}`].filter(Boolean).join(' · ')}</b></div><div className="expedition-levels">{Array.from({length:10},(_,i)=>i+1).map(value=><button key={value} disabled={value>maxUnlocked} className={value===level?'active':''} onClick={()=>setLevel(value)}><b>{value}</b><small>{value<=maxUnlocked?'Ouvert':'🔒'}</small></button>)}</div><div className="expedition-summary"><div><small>Puissance recommandée</small><b>{assessment.recommended.toLocaleString('fr-FR')}</b></div><div><small>Puissance actuelle</small><b className={assessment.verdict.key}>{assessment.power.toLocaleString('fr-FR')}</b></div><div><small>Récompense</small><b>{typeof data.reward==='number'?`${activity.rewardIcon} ${data.reward.toLocaleString('fr-FR')}`:[data.reward.minor&&`🔹 ${data.reward.minor}`,data.reward.major&&`🔷 ${data.reward.major}`,data.reward.mythic&&`💠 ${data.reward.mythic}`].filter(Boolean).join(' · ')}</b></div><div><small>Coût</small><b>{expeditionProgress.seals>0?'🔑 1 Sceau':'Entraînement'}</b></div><div><small>Équipement</small><b>{Math.round(data.gearChance*100)} % · {(EXPEDITION_SET_POOLS[selected]||[]).map(id=>SETS[id]).filter(Boolean).map(set=>set.name).join(' · ')}</b></div></div><button className="content-enemy-info-button expedition-enemy-info-button" onClick={()=>setEnemyInfo(expeditionMission.enemies)}>ⓘ Ennemis du niveau {level}</button><div className="expedition-mechanics"><Readiness assessment={assessment}/><h3>Mécaniques</h3>{data.mechanics.map(text=><p key={text}>⚠️ {text}</p>)}</div><button className="expedition-launch" disabled={level>maxUnlocked} onClick={launch}>{expeditionProgress.seals>0?`Lancer · Niveau ${level}`:'Mode entraînement · Aucune récompense'}</button></article>{enemyInfo&&<EnemyInfoModal title={`Ennemis · ${activity.name} niveau ${level}`} subtitle={`${activity.icon} ${activity.rewardName} · Expédition`} enemies={enemyInfo} onClose={()=>setEnemyInfo(null)} note={`Statistiques calculées pour le niveau ${level}. Chaque rôle explique la priorité de ciblage.`}/>}</section>;
}
