import React,{useState}from'react';
import{useGame}from'../store/GameContext';
import{RAIDS,raidLevelData,createRaidMission,RAID_DAILY_ATTEMPTS}from'../data/raids';
import{SETS,RAID_SETS}from'../data/items';
import EnemyInfoModal from'../components/EnemyInfoModal';


const Readiness=({assessment})=><section className={`readiness-panel ${assessment.verdict.key}`}><header><div><small>PRÉPARATION RÉELLE</small><b>{assessment.verdict.icon} {assessment.verdict.label}</b></div><strong>{assessment.score}/100</strong></header><div className="readiness-bars"><span><small>Dégâts</small><i><b style={{width:`${assessment.checks.damage}%`}}/></i><em>{assessment.checks.damage}%</em></span><span><small>Survie</small><i><b style={{width:`${assessment.checks.survival}%`}}/></i><em>{assessment.checks.survival}%</em></span><span><small>Tempo</small><i><b style={{width:`${assessment.checks.tempo}%`}}/></i><em>{assessment.checks.tempo}%</em></span></div><div className="readiness-tags"><span>💚 Soins : {assessment.checks.sustain}</span><span>✨ Purification : {assessment.checks.cleanse}</span><span>🧯 Feu : {assessment.checks.fire}</span></div>{assessment.gaps.length>0&&<ul>{assessment.gaps.slice(0,4).map(gap=><li key={gap}>⚠️ {gap}</li>)}</ul>}</section>;
export default function RaidsPage({setPage}){
  const{raidProgress,summonerProfile,teamPower,assessMission,requestMissionStart}=useGame();
  const[selected,setSelected]=useState('heartforge'),[level,setLevel]=useState(1),[enemyInfo,setEnemyInfo]=useState(null),[message,setMessage]=useState(''),[launching,setLaunching]=useState(false);
  const raid=RAIDS.find(item=>item.id===selected)||RAIDS[0],unlocked=summonerProfile.level>=raid.unlockLevel;
  const maxUnlocked=raid.id==='heartforge'?Math.min(10,(raidProgress.completed?.[raid.id]||0)+1):1,data=raidLevelData(raid.id,level),raidMission=raid.status==='active'?createRaidMission(raid.id,level):null,assessment=raidMission?assessMission(raidMission):null;
  const launch=()=>{if(launching||raid.status!=='active'||!unlocked||level>maxUnlocked)return;setLaunching(true);const result=requestMissionStart(createRaidMission(raid.id,level));if(result.ok)setPage('battle');else setMessage(result.message||'Impossible de préparer ce Raid.');setTimeout(()=>setLaunching(false),250)};
  return <section className="raids-page">
    <div className="raids-heading"><div><h2>⚔️ Raids d’Azerune</h2><p>Affronte des boss mécaniques après la Campagne. Ignifuge prépare à Rhazakar; Incendiaire et Furie volcanique restent exclusifs au Raid.</p></div><div className="raid-attempts"><small>Tentatives récompensées</small><b>{raidProgress.attempts}/{RAID_DAILY_ATTEMPTS}</b></div></div>
    <div className="raid-list">{RAIDS.map(item=>{const open=summonerProfile.level>=item.unlockLevel;return <button key={item.id} className={`${selected===item.id?'selected':''} ${item.status!=='active'?'coming':''}`} onClick={()=>{setSelected(item.id);setLevel(1)}}><span>{open?item.icon:'🔒'}</span><strong>{item.name}</strong><small>{item.boss}</small><em>{item.status==='active'?`Progression ${raidProgress.completed?.[item.id]||0}/10`:'Prochainement'}</em><b>Niveau Invocateur {item.unlockLevel}</b></button>})}</div>
    <article className={`raid-detail raid-${raid.id}`}><div className="raid-boss"><span>{raid.icon}</span><div><h3>{raid.name}</h3><b>{raid.boss}</b><p>{raid.description}</p></div><div><small>Élément</small><strong>{raid.element}</strong></div></div>
      {raid.status==='active'?<><div className="raid-levels">{Array.from({length:10},(_,index)=>index+1).map(value=><button key={value} disabled={!unlocked||value>maxUnlocked} className={level===value?'active':''} onClick={()=>setLevel(value)}><b>{value}</b><small>{value<=maxUnlocked?'Ouvert':'🔒'}</small></button>)}</div>
      <div className="raid-level-panel"><div className="raid-level-summary"><div><small>Niveau sélectionné</small><b>Niveau {level}</b></div><div><small>Puissance recommandée</small><b>{assessment.recommended.toLocaleString('fr-FR')}</b></div><div><small>Puissance actuelle</small><b className={assessment.verdict.key}>{assessment.power.toLocaleString('fr-FR')}</b></div><div><small>Éruption</small><b>{data.eruptionAt} charges</b></div></div>
      <button className="content-enemy-info-button raid-enemy-info-button" disabled={!raidMission} onClick={()=>raidMission&&setEnemyInfo(raidMission.enemies)}>ⓘ Ennemis du niveau {level}</button><div className="raid-mechanics"><Readiness assessment={assessment}/><h3>Mécaniques actives</h3>{data.mechanics.map(([name,description],index)=><div key={name} className={index===data.mechanics.length-1?'new-mechanic':''}><span>{index===0?'🔥':'⚠️'}</span><div><b>{name}</b><small>{description}</small></div></div>)}</div>
      <div className="raid-exclusive-sets"><div><small>SETS EXCLUSIFS DU RAID</small><b>Incendiaire et Furie volcanique</b><p>Le set Ignifuge s’obtient en Campagne pour préparer Rhazakar.</p></div><div>{(RAID_SETS[raid.id]||[]).map(setId=>{const set=SETS[setId];return <span key={setId} className={`raid-set-chip raid-set-${setId}`}><strong>{set.icon} {set.name}</strong><small>{set.pieces} pièces · {set.bonus}</small></span>})}</div></div><div className="raid-loot"><h3>Butin du niveau {level}</h3><span>🪙 {data.reward.gold}</span><span>💎 {data.reward.gems}</span>{data.reward.stones>0&&<span>🔥 {data.reward.stones}</span>}<span>🎁 Équipement {data.loot.stars}★ · qualité {data.loot.minQuality} minimum</span></div>
      <button className="raid-launch" disabled={!unlocked||level>maxUnlocked} onClick={launch}>{!unlocked?`Niveau Invocateur ${raid.unlockLevel} requis`:level>maxUnlocked?'Niveau précédent requis':`Lancer le raid · Niveau ${level}`}</button></div></>:<div className="raid-coming"><span>🚧</span><h3>Raid en préparation</h3><p>Les mécaniques et les dix niveaux sont annoncés. Une prochaine mise à jour rendra ce raid jouable.</p></div>}
    </article>{enemyInfo&&<EnemyInfoModal title={`Ennemis · ${raid.name} niveau ${level}`} subtitle={`${raid.icon} ${raid.boss} · Raid`} enemies={enemyInfo} onClose={()=>setEnemyInfo(null)} note={`Statistiques calculées pour le niveau ${level}. Les rôles mécaniques sont indiqués sous chaque ennemi.`}/>}
  </section>;
}
